#  DO-NOT-REMOVE begin-copyright-block
# QFlex consists of several software components that are governed by various
# licensing terms, in addition to software that was developed internally.
# Anyone interested in using QFlex needs to fully understand and abide by the
# licenses governing all the software components.
#
# ### Software developed externally (not by the QFlex group)
#
#     * [NS-3] (https://www.gnu.org/copyleft/gpl.html)
#     * [QEMU] (http://wiki.qemu.org/License)
#     * [SimFlex] (http://parsa.epfl.ch/simflex/)
#     * [GNU PTH] (https://www.gnu.org/software/pth/)
#
# ### Software developed internally (by the QFlex group)
# **QFlex License**
#
# QFlex
# Copyright (c) 2021, Parallel Systems Architecture Lab, EPFL
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of the Parallel Systems Architecture Laboratory, EPFL,
#       nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written
#       permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE PARALLEL SYSTEMS ARCHITECTURE LABORATORY,
# EPFL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
# THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  DO-NOT-REMOVE end-copyright-block

name: build-tests
on: 
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_PRIVATE_KEY }}"
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          extensions: 'hpp,cpp,c'
          clangFormatVersion: 6
          inplace: True
          style: file 
      - uses: EndBug/add-and-commit@v7
        id: commit_step
        with:
          author_name: "GHA Integration[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          default_author: user_info
          message: 'Commit changes from clang-format'
      - name: "Fail if formatter committed changes."
        if: ${{ steps.commit_step.outputs.committed == 'true' }}
        run: exit 1

  build-with-syspkgs:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        include:
          - sim: "KeenKraken"
          - sim: "KnottyKraken"
    env:
      DEPS: cmake libboost-all-dev
      SIMULATOR: ${{ matrix.sim }}
    steps:
      - name: Install system dependencies
        run: sudo apt update -qq && sudo apt upgrade -y && sudo apt install -y $DEPS
      - name: Checkout flexus
        uses: actions/checkout@v2
      - name: Checkout libqflex dependency
        uses: actions/checkout@v2
        with:
          repository: parsa-epfl/libqflex
          path: libqflex-checkout
      - name: Move libqflex to parent dir
        run: mv libqflex-checkout ../libqflex
      - name: Build flexus
        run: ./tests/build_flexus.sh $SIMULATOR

  build-with-frozenpkgs:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        include:
          - sim: "KeenKraken"
          - sim: "KnottyKraken"
    env:
      DEPS: cmake
      SIMULATOR: ${{ matrix.sim }}
    steps:
      - name: Install system dependencies
        run: sudo apt update -qq && sudo apt upgrade -y && sudo apt install -y $DEPS
      - name: Checkout flexus
        uses: actions/checkout@v2
      - name: Checkout libqflex dependency
        uses: actions/checkout@v2
        with:
          repository: parsa-epfl/libqflex
          path: libqflex-checkout
      - name: Move libqflex to parent dir
        run: mv libqflex-checkout ../libqflex
      - name: Build frozen pkg versions
        run: ./.github/scripts/build_frozen_pkgs.sh
      - name: Build flexus
        run: ./tests/build_flexus.sh $SIMULATOR
  
  run-harness-with-syspkgs:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DEPS: cmake libboost-all-dev
      ALL_TESTS: "MemoryLoopbackTestFixture*"
    steps:
      - name: Install system dependencies
        run: sudo apt update -qq && sudo apt upgrade -y && sudo apt install -y $DEPS
      - name: Checkout flexus
        uses: actions/checkout@v2
      - name: Checkout libqflex dependency
        uses: actions/checkout@v2
        with:
          repository: parsa-epfl/libqflex
          path: libqflex-checkout
      - name: Move libqflex to parent dir
        run: mv libqflex-checkout ../libqflex
      - name: Build harness
        run: ./tests/build_harness.sh
      - name: Run harness
        run: ./tests/run_harness.sh $ALL_TESTS

  run-harness-with-frozenpkgs:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DEPS: cmake
      ALL_TESTS: "MemoryLoopbackTestFixture*"
    steps:
      - name: Install system dependencies
        run: sudo apt update -qq && sudo apt upgrade -y && sudo apt install -y $DEPS
      - name: Checkout flexus
        uses: actions/checkout@v2
      - name: Checkout libqflex dependency
        uses: actions/checkout@v2
        with:
          repository: parsa-epfl/libqflex
          path: libqflex-checkout
      - name: Move libqflex to parent dir
        run: mv libqflex-checkout ../libqflex
      - name: Build frozen pkg versions
        run: ./.github/scripts/build_frozen_pkgs.sh
      - name: Build harness
        run: ./tests/build_harness.sh
      - name: Run harness
        run: ./tests/run_harness.sh $ALL_TESTS
